<a href="https://colab.research.google.com/github/thlystrd/LinearAlgebra_2ndsem/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Laboratory 4 : Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intemrediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

The import keyword can make code from one code available in another. The import function is essential in organizing your codes and saving time by reusing what you imported. [1]

> Numerical Programming Libraries:
> *   **Numerical Python** is also known as ***numpy*** and uses ***np*** as a coding shortcut. It is a library of multidimensional arrays as well as a set of algorithms for manipulating which is helpful in conducting mathematical and logical array operations. [2]
> *   **Matplotlib** is also known as ***matplotlib.pyplot*** and uses ***plt*** as a coding shortcut. It is a library that helps in easier visualization and analysis of the data. This will help display the matrices.  [3]
> *   **SciPy** is also known as ***scipy.linalg*** and uses ***la*** as a coding shortcut. It is an open source library designed for science and engineering tasks.
This usually deals with linear algebra to help us perform tasks like matrix calculations. [4]


> Running the import code cell before everything below is important for your codes to function.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

Transposition is the act of transposing a matrix by switching its rows and columns to obtain its transpose. This is attained by exhanging an array A from array A [i] [j] into A [j] [i] [x]. In python, this can be done in a two ways, with the use of np.transpose(A) or A.T.

$$I = \begin{bmatrix} 11 & -3 & 20\\20 & -6 & 11 \\ 12 & 19 & 30\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 11 & 20 & 12\\-3 & -6 & 19 \\ 20 & 11 & 30\end{bmatrix}$$

In [ ]:
CUTIE = np.array([
    [11 ,-3, 20],
    [20, -6, 11],
    [12, 19, 30]
])
CUTIE

array([[11, -3, 20],
       [20, -6, 11],
       [12, 19, 30]])

In [ ]:
CUTIE1 = np.transpose(CUTIE)
CUTIE1


array([[11, 20, 12],
       [-3, -6, 19],
       [20, 11, 30]])

In [ ]:
CUTIE2 = CUTIE.T
CUTIE2

array([[11, 20, 12],
       [-3, -6, 19],
       [20, 11, 30]])

In [ ]:
np.array_equiv(CUTIE1, CUTIE2)

True

In [ ]:
PATOOTIE = np.array([
    [8,6,2,3,1],
    [1,8,2,5,1],
    [1,8,7,6,9],
    [8,5,2,6,7]
])
PATOOTIE.shape

(4, 5)

In [ ]:
np.transpose(PATOOTIE).shape

(5, 4)

In [ ]:
PATOOTIE.T.shape

(5, 4)

## Dot Product / Inner Product

Dot Product or Inner Product delivers the same result. It is an algebraic operation that operates matrices of two equal-sized vectors and returns a single scalar. The two matrices must be nonscalar, and their final dimensions must match. As an example,  $NANA$ and $LALA$ are two matrices of identical shape, and they will be labeled as:

$$NANA = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, LALA = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The assigned values for $NANA$ and $LALA$ are:

$$NANA = \begin{bmatrix}15&21\\ -9&17\end{bmatrix}, LALA = \begin{bmatrix}-8&10\\ 21&12\end{bmatrix}$$

We will acquire the sum of vector products by row-column pairings, which will return to a single number. The process for this algebraic operation can be done by following this:
$$NANA \cdot LALA= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

Once substituted, the matrix will look like this, and the dot product will be shown as:
$$NANA \cdot LALA= \begin{bmatrix} 15*-8 + 21*21 & 15*10 + 21*12 \\  -9*-8 + 17*21 & -9*10 + 17*12 \end{bmatrix} = \begin{bmatrix} 321 & 402 \\429 & 114 \end{bmatrix}$$



In [ ]:
NANA = np.array([
    [15,21],
    [-9,17]
])
LALA = np.array([
    [-8,10],
    [21,12]
])

In [ ]:
np.dot(NANA,LALA)

array([[321, 402],
       [429, 114]])

In [ ]:
NANA.dot(LALA)

array([[321, 402],
       [429, 114]])

In [ ]:
NANA @ LALA

array([[321, 402],
       [429, 114]])

In [ ]:
np.matmul(NANA,LALA)

array([[321, 402],
       [429, 114]])

##Rule 1: The inner dimensions of the two matrices in question must be the same. 



During matrix multiplication, the main condition is that the inner dimensions of the two matrices must be the same in order to result in a matrix with the same dimensions as that of the outer dimensions of the multiplied matrices. An array A with dimensions of **m×n** and array B with dimensions **n×p** are multiplicable as they have the same inner dimensions. Multiplying these arrays would result in a matrix with dimensions **m×p**. 

$$YZEL = \begin{bmatrix}6&7&3&-1\\-9&-2&7&4\\6&1&5&-4\end{bmatrix}, OREO = \begin{bmatrix}8&-4&9&-5\\1&8&-3&1\\-1&4&9&8\\-9&2&3&-7\end{bmatrix}, MOCHA = \begin{bmatrix}-9&-5&6\\6&-8&0\\8&-7&1\\2&-3&4\end{bmatrix}$$


In [ ]:
YZEL = np.array([
    [6,7,3,-1],
    [-9,-2,7,4],
    [6,1,5,-4]
])
OREO = np.array([
    [8,-4,9,-5],
    [1,8,-3,1],
    [-1,4,9,8],
    [-9,2,3,-7]
])
MOCHA = np.array([
    [-8,-5,6],
    [6,-8,0],
    [8,-7,1],
    [2,-3,4]
])
print(YZEL.shape)
print(OREO.shape)
print(MOCHA.shape)

(3, 4)
(4, 4)
(4, 3)


In [ ]:
YZEL @ MOCHA

array([[  16, -104,   35],
       [ 124,    0,  -31],
       [ -10,  -61,   25]])

In [ ]:
OREO @ MOCHA

array([[ -26,  -56,   37],
       [  18,  -51,    7],
       [ 120, -114,   35],
       [  94,   29,  -79]])

In [ ]:
YZEL @ OREO.T

array([[ 52,  52,  41, -24],
       [-21, -42,  96,  70],
       [109,  -5,  11,  -9]])

In [ ]:
KAR = np.array([
    [-6,11,20,-2,-3,11,20,20]
])
REN = np.array([
    [12,19,20,-1,-3,11,20,20]
])
print(KAR.shape)
print(REN.shape)

(1, 8)
(1, 8)


In [ ]:
REN.T @ KAR

array([[ -72,  132,  240,  -24,  -36,  132,  240,  240],
       [-114,  209,  380,  -38,  -57,  209,  380,  380],
       [-120,  220,  400,  -40,  -60,  220,  400,  400],
       [   6,  -11,  -20,    2,    3,  -11,  -20,  -20],
       [  18,  -33,  -60,    6,    9,  -33,  -60,  -60],
       [ -66,  121,  220,  -22,  -33,  121,  220,  220],
       [-120,  220,  400,  -40,  -60,  220,  400,  400],
       [-120,  220,  400,  -40,  -60,  220,  400,  400]])

## Rule 2: Dot Product has special properties



Dot Product has five unique properties to discuss, namely:
1. Commutative Property - operates two matrices in a commutative way which result in unequal matrices and can be stated as: 
$A \cdot B \neq B \cdot A$

2. Associative Property - operates three or more matrices by interchanging the operation position using parentheses and still getting the same answer. This can be stated as:
$A \cdot (B \cdot C) = (A \cdot B) \cdot C$ or $A\cdot(B+C) = A\cdot B + A\cdot C$
3. Distributive Property - operates three or more matrices by distributing the operations for the matrices inside the parentheses and still getting the same answer. This can be stated as:
$(B+C)\cdot A = B⋅ A + C\cdot A$
4. Identity Property - a function used to return the identity of a given matrix. It can be stated as: 
 $A⋅ I = A$
5. Multiplicative Property of Zero - a function used to return the shape of a given matrix displaying zeroes in it. It can be stated as:
$A\cdot \emptyset = \emptyset$ 
 

In [ ]:
YAW = np.array([
    [8,3,5],
    [7,5,4],
    [1,0,9]
])
KOH = np.array([
    [-9,5,6],
    [7,-2,9],
    [4,-8,0]
])
NAH = np.array([
    [7,8,-4],
    [1,0,-5],
    [1,1,0]
])
POH = np.zeros((3,3))

In [ ]:
one = YAW.dot(KOH)
one1 = KOH.dot(YAW)
print(f'{one}  \n\n{one1}\n')
print(f'Array Equality: {np.array_equal(one,one1)}')

[[-31  -6  75]
 [-12  -7  87]
 [ 27 -67   6]]  

[[-31  -2  29]
 [ 51  11 108]
 [-24 -28 -12]]

Array Equality: False


In [ ]:
two = YAW.dot(KOH.dot(NAH))
two2 = (YAW.dot(KOH)).dot(NAH)
print(f'{two}  \n\n{two2}\n')
print(f'Array Equality: {np.array_equal(two,two2)}')

[[-148 -173  154]
 [  -4   -9   83]
 [ 128  222  227]]  

[[-148 -173  154]
 [  -4   -9   83]
 [ 128  222  227]]

Array Equality: True


In [ ]:
three = YAW.dot(KOH+NAH)
three3 = (YAW.dot(KOH))+(YAW.dot(NAH))
print(f'{three}  \n\n{three3}\n')
print(f'Array Equality: {np.array_equal(three,three3)}')

[[ 33  63  28]
 [ 46  53  34]
 [ 43 -50   2]]  

[[ 33  63  28]
 [ 46  53  34]
 [ 43 -50   2]]

Array Equality: True


In [ ]:
four = (KOH+NAH).dot(YAW)
four4 = (KOH.dot(YAW))+(NAH.dot(YAW))
print(f'{four}  \n\n{four4}\n')
print(f'Array Equality: {np.array_equal(four,four4)}')

[[ 77  59  60]
 [ 54  14  68]
 [ -9 -20  -3]]  

[[ 77  59  60]
 [ 54  14  68]
 [ -9 -20  -3]]

Array Equality: True


In [ ]:
five = YAW.dot(np.identity(3))
five5 = YAW
print(f'{five}  \n\n{five5}\n')
print(f'Array Equality: {np.array_equal(five,five5)}')

[[8. 3. 5.]
 [7. 5. 4.]
 [1. 0. 9.]]  

[[8 3 5]
 [7 5 4]
 [1 0 9]]

Array Equality: True


In [ ]:
six = YAW.dot(POH)
six6 = (POH)
print(f'{six}  \n\n{six6}\n')
print(f'Array Equality: {np.array_equal(six,six6)}')

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]  

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array Equality: True


In [ ]:
YAW.dot(np.zeros(YAW.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
TAH = np.zeros(YAW.shape)
TAH

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
LAH = YAW.dot(np.zeros(YAW.shape))
LAH

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(TAH,LAH)

True

In [ ]:
null_mat = np.empty(YAW.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(TAH,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

A determinant is a numerical output of an inputted square matrix array. These are useful in the analysis of solutions in linear algebra.  

Properties of determinants include [x]:
*   det $A^T$ = det A
*   det (AB) = det (A) det (B)
*   If a row or column of A is zero, det A = 0.
*   The determinant of an upper or lower triangular matrix is the product of its diagonal elements.
* $ A^-1 = adj(A)/det(A)  $

In [ ]:
AY = np.array([
    [12,19],
    [20,-1]
])
np.linalg.det(AY)

-392.0000000000002

In [ ]:
NA = np.array([
    [-2,-9,20],
    [-3,18,20],
    [-7,13,21]
])
np.linalg.det(NA)

2197.000000000001

In [ ]:
KO = np.array([
    [7,8,4,5],
    [8,7,6,9],
    [2,5,9,1],
    [2,6,1,0]
])
np.linalg.det(KO)

-488.00000000000017

## Inverse

The inverse of a matrix is an algebraic operation used to find the solution of a system of linear equations. The matrix should not include 0 as its determinant. The inverse of a matrix is known as its reciprocal. The rechecking of an inverse matrix can be done using the dot productin which the inverse of a matrix will be multiplied by the original matrix to solve for the identity matrix. 
The equation is stated as: $$AN ⋅ AN^{-1}=I$$



In [ ]:
AN = np.array([
    [7,3],
    [2,5]
])
np.array(AN @ np.linalg.inv(AN))

array([[1.00000000e+00, 5.55111512e-17],
       [4.16333634e-17, 1.00000000e+00]])

In [ ]:
AN = np.array([
    [7,3],
    [2,5]
])
np.array(AN @ np.linalg.inv(AN), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
TOK = np.array([
    [-1,8,7,3],
    [8,5,3,-5],
    [0,1,8,9],
    [-6,4,1,3]
])

NA = np.linalg.inv(TOK)
np.array(TOK @ NA,dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
TU = np.array([
    [-3,-8,64],
    [12,-5,62],
    [12,12,-1]
])
LOG = np.array([
    [58,60,21]
])
ME = TU @ LOG.T
ME

array([[ 690],
       [1698],
       [1395]])

## Task 1

Task one (1) is an application of the concepts that have been taught during the lesson concerning the dot product/inner product matrix operation. This task contains the 5 special properties under the rule two (2) of the dot product operation, mainly:
* Commutative Property
* Associative Property
* Distributive Property
* Identity Property
* Multiplicative Property of Zero





In [ ]:
A = np.array([
    [1,3,5,7],
    [3,6,9,12],
    [6,12,18,24],
    [12,24,36,48]
])
B = np.array([
    [0,2,4,6],
    [2,4,6,8],
    [4,8,12,16],
    [8,16,24,32]
])
C = np.array([
    [2,0,2,2],
    [2,0,2,1],
    [2,0,2,0],
    [2,0,1,9]
])
D = np.zeros((4,4))

In [ ]:
one = A.dot(B)
one1 = B.dot(A)
print(f'Commutative Property: \n{one}  \n\n{one1}\n\n')
print(f'Array Equality: {np.array_equal(one,one1)}')

Commutative Property: 
[[  82  166  250  334]
 [ 144  294  444  594]
 [ 288  588  888 1188]
 [ 576 1176 1776 2376]]  

[[ 102  204  306  408]
 [ 146  294  442  590]
 [ 292  588  884 1180]
 [ 584 1176 1768 2360]]


Array Equality: False


In [ ]:
two = A.dot(B.dot(C))
two2 = (A.dot(B)).dot(C)
print(f'Associative Property: \n{two}  \n\n{two2}\n\n')
print(f'Array Equality: {np.array_equal(two,two2)}')

Associative Property: 
[[ 1664     0  1330  3336]
 [ 2952     0  2358  5928]
 [ 5904     0  4716 11856]
 [11808     0  9432 23712]]  

[[ 1664     0  1330  3336]
 [ 2952     0  2358  5928]
 [ 5904     0  4716 11856]
 [11808     0  9432 23712]]


Array Equality: True


In [ ]:
three = A.dot(B+C)
three3 = (A.dot(B))+(A.dot(C))
print(f'Distibutive Property: \n{three}  \n\n{three3}\n\n')
print(f'Array Equality: {np.array_equal(three, three)}')

Distibutive Property: 
[[ 114  166  275  402]
 [ 204  294  492  714]
 [ 408  588  984 1428]
 [ 816 1176 1968 2856]]  

[[ 114  166  275  402]
 [ 204  294  492  714]
 [ 408  588  984 1428]
 [ 816 1176 1968 2856]]


Array Equality: True


In [ ]:
four = (B+C).dot(A)
four4 = (B.dot(A))+(C.dot(A))
print(f'Distibutive Property: \n{four}  \n\n{four4}\n\n')
print(f'Array Equality: {np.array_equal(four,four4)}')

Distibutive Property: 
[[ 140  282  424  566]
 [ 172  348  524  700]
 [ 306  618  930 1242]
 [ 700 1410 2120 2830]]  

[[ 140  282  424  566]
 [ 172  348  524  700]
 [ 306  618  930 1242]
 [ 700 1410 2120 2830]]


Array Equality: True


In [ ]:
five = A.dot(np.identity(4))
five5 = A
print(f'Identity Property: \n{five}  \n\n{five5}\n\n')
print(f'Array Equality: {np.array_equal(five, five5)}')

Identity Property: 
[[ 1.  3.  5.  7.]
 [ 3.  6.  9. 12.]
 [ 6. 12. 18. 24.]
 [12. 24. 36. 48.]]  

[[ 1  3  5  7]
 [ 3  6  9 12]
 [ 6 12 18 24]
 [12 24 36 48]]


Array Equality: True


In [ ]:
six = A.dot(D)
six6 = (D)
print(f'Multiplicative Property of Zero: \n{six}  \n\n{six6}\n\n')
print(f'Array Equality: {np.array_equal(six,six6)}')

Multiplicative Property of Zero: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]  

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Array Equality: True
