<a href="https://colab.research.google.com/github/thlystrd/LinearAlgebra_2ndsem/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
##Laboratory 2: Matrices

Now that you have a fundamental knowledge about Python, we'll try to look into greater dimensions.

###Objectives
At the end of this activity you will be able to:

  1. Be familiar with matrices and their relation to linear equations.
  2. Perform basic matrix operations.
  3. Program and translate matrix equations and operations using Python.

#Discussion

The import keyword can make code from one code available in another. The import function is essential in organizing your codes and saving time by reusing what you imported. [1]

> Numerical Programming Libraries:
> *   **Numerical Python** is also known as ***numpy*** and uses ***np*** as a coding shortcut. It is a library of multidimensional arrays as well as a set of algorithms for manipulating which is helpful in conducting mathematical and logical array operations. [2]
> *   **Matplotlib** is also known as ***matplotlib.pyplot*** and uses ***plt*** as a coding shortcut. It is a library that helps in easier visualization and analysis of the data. This will help display the matrices.  [3]
> *   **SciPy** is also known as ***scipy.linalg*** and uses ***la*** as a coding shortcut. It is an open source library designed for science and engineering tasks.
This usually deals with linear algebra to help us perform tasks like matrix calculations. [4]


> Running the import code cell before everything below is important for your codes to function.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

##Matrices

Matrix is a two-dimensional rectangular array that stores data in rows and columns. The data you can input on a matrix can be integers, strings, equations, symbols, etc. It is a data structure that operates mathematical and scientific operations. [5]

We have $A$, $B$, and $C$ as system of equations.

$$
A = \left\{
    \begin{array}\
        11x + 6y \\ 
        19x + 3y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        2x + 7y + 3z \\ 
        9x + 2y + 8z \\
        4x + 7y + 2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        -w + 12x - 3y + 4z \\ 
        -3w + 13x - 7y + z \\
        -2w + 11x - 9y + 2z
    \end{array}
\right. $$

We could see that $A$ is a system of 2 equations with 2 parameters, $B$ is a system of 3 equations with 3 parameters and $C$ is a system of 4 equations and 4 parameters. The matrix representation for the system of linear combinations above represented as:

$$
A=\begin{bmatrix} 11 & 6 \\ 19 & 3\end{bmatrix} \\
B=\begin{bmatrix} 2 & 7 & 3 \\ 9 & 2 & 8 \\ 4 & 7 & 2\end{bmatrix}\\
C=\begin{bmatrix} -1 & 12 & -3 & 4 \\ -3 & 13 & -7 & 1 \\ -2 & 11 & -9 & 2\end{bmatrix}
$$


So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in
here in Python

##Declaring Matrices

The system of linear equations can be represented as a matrix consisting of a row and column. The integers, strings, equations, symbols, and etc. inputted inside the matrices are called as *elements* or *entry*. A matrix has the size of ***$i$ x $j$*** in which **$i$** represents the matrix's column and **$j$** represents the matrix's row. Columns goes in a vertical way making the elements appear as a list from top to bottom while rows are arranged horizontally making the elements appear as an array-like or in a linear form. This can be represented
just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $ai,j$. 

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [ ]:
## Since we’11 keep on describing matrices. Let's make a function.
def describe_mat (matrix):
   print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
K = np.array([
  [11, 12],
  [13, 11]
])
describe_mat(K)

Matrix:
[[11 12]
 [13 11]]

Shape:	(2, 2)
Rank:	2



In [ ]:
M = np.array([
    [6,1,2],
    [1,2,9]
])
describe_mat(M)

Matrix:
[[6 1 2]
 [1 2 9]]

Shape:	(2, 3)
Rank:	2



In [ ]:
## Declaring a 3 x 2 matrix
A = np.array([
    [18, 22],
    [35, 41],
    [71, 18]
])
describe_mat(A)

Matrix:
[[18 22]
 [35 41]
 [71 18]]

Shape:	(3, 2)
Rank:	2



In [ ]:
T = np.array([1,2,3,4])
describe_mat(T)

Matrix:
[1 2 3 4]

Shape:	(4,)
Rank:	1



##Categorizing Matrices

**Matrices** can be categorized according to their *Shapes* annd according to their *Element Values*. 
> Matrix According to Shape:
> * Row and Column Matrix
> * Square Matrix

>Matrix According to Element Values:
> * Null Matrix
> * Zero Matrix
> * Ones Matrix
> * Diagonal Matrix
> * Identity Matrix
> * Upper Triangular Matrix
> * Lower Triangular Matrix

###According to shape

#### Row and Column Matrices

Row and Column Matrices are necessary for matrix computations. The shape of row matrices would be  $1×j$ given that a row is array-like or arranged horizontally. The shape of Column Matrices would be $i×1$ given that a column is list-like or arranged vertically.

In [ ]:
## Declaring a Row Matrix
row_yzel=np.array([
    [12, 19, 20, -1]
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_oreo=np.array([
    [-6, 11, 20, -2]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat (row_yzel)
describe_mat (row_oreo)

Matrix:
[[12 19 20 -1]]

Shape:	(1, 4)
Rank:	2

Matrix:
[[-6 11 20 -2]]

Shape:	(1, 4)
Rank:	2



In [ ]:
## Declaring a Column Matrix
col_mocha=np. array ([
[-2],
[-9],
[20],
[20]
])## this is a 2-D Matrix with a shape of (3,1)
describe_mat (col_mocha)


Matrix:
[[-2]
 [-9]
 [20]
 [20]]

Shape:	(4, 1)
Rank:	2



#### Square Matrices

Square Matrices are are consists of rows and columns that are equal to each other. A matrix can be considered as square if $i = j$. Matrix descriptor function can determine if a matrix is square or not.

In [ ]:
def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_kar= np.array([
  [2,9,20],
  [3,18,20],
  [7,13,21]
])

non_square_kar = np. array([
  [2,6,20],
  [3,18,21]
])
describe_mat(square_kar)
describe_mat(non_square_kar)



Matrix:
[[ 2  9 20]
 [ 3 18 20]
 [ 7 13 21]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[ 2  6 20]
 [ 3 18 21]]

Shape:	(2, 3)
Rank:	2
Is Square: False



### According to element values

#### Null Matrix

A Null Matrix is a matrix that does not have any element, entry, row, column, or shape. This matrix contains nothing; hence its name null.

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
null_meh = np.array([])
describe_mat(null_meh)

Matrix is Null


####Zero Matrix

Zero matrix displays an element of zero given a shape or type. Zero matrix can be inputted on a shape of $i$ x $j$. The matrix will display a resultant matrix that is filled with zeros in accordance to the given size. 

In [ ]:
zero_na_ba_talaga = np.zeros((1,2))
zero_na_po_ba = np.zeros((2,2) )
zero_na_nga_daw = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_na_ba_talaga}')
print(f'Zero Square Matrix: \n{zero_na_po_ba}')
print(f'Zero Rectangular Matrix: \n{zero_na_nga_daw}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


####Ones Matrix

Ones matrix displays an element of one given a shape or type. Ones matrix can be inputted on a shape of $i$ x $j$. The matrix will display a resultant matrix that is filled with ones in accordance to the given size. 

In [ ]:
ones_upon_a_time = np.ones((1,2))
ones_in_a_while = np.ones((2,2) )
ones_a_lifetime = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_upon_a_time}')
print(f'Ones Square Matrix: \n{ones_in_a_while}')
print(f'Ones Rectangular Matrix: \n{ones_a_lifetime}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


####Diagonal Matrix

Diagonal Matrix is a matrix that contains numerical values placed in a diagonal line with zeroes to fill in the blank spaces of the matrix [6]. This is mostly used to reperesent the scale of the vectors found in linear equations. 

In [ ]:
np.array([
        [12,19,1],
        [3,11,20],
        [6,11,2]
  ])
  # a[1,1], a[2,2], ... a[n-1,n-1]

array([[12, 19,  1],
       [ 3, 11, 20],
       [ 6, 11,  2]])

In [ ]:
hi = np.diag([-3,11,20,20])
hi.shape[0] == hi.shape[1]
hi

array([[-3,  0,  0,  0],
       [ 0, 11,  0,  0],
       [ 0,  0, 20,  0],
       [ 0,  0,  0, 20]])

####Identity Matrix

Identity Matrix is a type of diagonal square matrix that is specifically filled with ones placed along its diagonal line and zeroes everywhere else to fill up the matrix [7]. This is called an identity matrix because when it is multiplied to any other matrix the result contains the contents of the matrix itself. 

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.identity(11)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

####Upper Triangular Matrix

Upper Triangular Matrix is a type of matrix that is filled with zeroes below the matrix's diagonal creating a zero triangle. This may or may not contain a parameter to specify if the zero triangle would be the main diagonal (K = 0), which is the default, above the main diagonal (K > 0), or below the main diagonal (K < 0) [8]. 

In [ ]:
np.array([
        [1,2,3,4],
        [0,3,1,-1],
        [0,0,5,2],
        [0,0,0,2]
])

array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

####Lower Triangular Matrix

Lower Triangular Matrix is a type of matrix that is filled with zeroes above the matrix's diagonal creating a zero triangle. This may or may not contain a parameter to specify if the zero triangle would be the main diagonal (K = 0), which is the default, above the main diagonal (K > 0), or below the main diagonal (K < 0) [9]. 

In [ ]:
np.array([
   [6, 0, 0, 0],
   [8, 5, 0, 0],
   [9, 3, 7, 0],
   [4, 2, 1, 8]
])

array([[6, 0, 0, 0],
       [8, 5, 0, 0],
       [9, 3, 7, 0],
       [4, 2, 1, 8]])

##Practice

Given the linear combination below, try to create a corresponding matrix representing it.


$$\theta = 5x + 3y - z$$


$$
\theta = \begin{bmatrix} 5 & 3 & -1 \end{bmatrix} \\
$$

Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


$$
A=\begin{bmatrix} 1 & 2 & 1 \\ 0 & 4 & -1 \\ 0 & 0 & 10\end{bmatrix} \\
$$

Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


$$
G = \left\{\begin{array}
1x_1 + 7x_2 +8x_3\\
2x_1 + 2x2 + 2x_3\\
4x_1 + 6x_2 + 7x_3
\end{array}\right.
$$

Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

# Matrix Algebra

###Addition

Addition of Matrices operation requires that both matrices have the same dimensions. With this function, the components of the matrices are summed up element-wise creating an output with the same dimensions as the matrices used [10]. 

In [ ]:
M = np.array([
              [11, 19],
              [12, -6],
              [-3, 11]
])

E = np.array([
              [-2, -9],
              [-3, 18],
              [-7, 13]
])
M+E

array([[  9,  10],
       [  9,  12],
       [-10,  24]])

In [ ]:
3+M*E ##Broadcasting
# 3*np.ones(A.shape)+A

array([[ -19, -168],
       [ -33, -105],
       [  24,  146]])

###Subtraction

Similar to the addition of matrices, the subtraction of matrices operation requires that both matrices have the same dimensions. With this function, the components of the matrices are subtracted element-wise creating an output with the same dimensions as the matrices used. 

In [ ]:
Y = np.array([
              [8, 4],
              [2, 7],
              [3, 9]
])

O = np.array([
              [10, 12],
              [12, 13],
              [13, 14]
])

U = np.array([
              [-2, -2],
              [-1, -3],
              [-3, -4]
])
2*Y-O-U

array([[ 8, -2],
       [-7,  4],
       [-4,  8]])

In [ ]:
9-M*O ##Broadcasting
# 9*np.ones(M.shape)-M

array([[-101, -219],
       [-135,   87],
       [  48, -145]])

##Element-wise Multiplication

Element-wise multiplication of matrices operation requires that both matrices have the same dimensions. With this function, the components of the matrices are multiplied element-wise creating an output with the same dimensions as the matrices used [11]. 

In [ ]:
M*E
np.multiply(M,E)

array([[ -22, -171],
       [ -36, -108],
       [  21,  143]])

In [ ]:
2*Y*O*U

array([[ -320,  -192],
       [  -48,  -546],
       [ -234, -1008]])

In [ ]:
2*M*E

array([[ -44, -342],
       [ -72, -216],
       [  42,  286]])

In [ ]:
alpha=3**-11
M/(alpha+E)


array([[-5.50001552, -2.11111244],
       [-4.00000753, -0.33333323],
       [ 0.42857177,  0.84615348]])

In [ ]:
np.add(Y,O,U)

array([[18, 16],
       [14, 20],
       [16, 23]])

# Activity

### Task 1


Task 1 is all about the application of most of what has been conducted in this experiment mainly the categorization of matrices as the researchers created their own program that determined a given matrix’s shape, size, rank, whether or not it is a square matrix, whether or not it is an empty matrix, whether or not it is an identity matrix, whether or not it is a ones matrix, and whether or not it is a zeros matrix.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [ ]:
def mat_desc(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nSize:\t{matrix.size}\nRank:\t{matrix.ndim}\n')

  [r,c] = matrix.shape
  if r == c:
     print("Matrix is a Square Matrix")
  else:
     print("Matrix is Not a Square Matrix")

  Emat = not np.any
  if Emat:
    print("Matrix is Empty")
  else:
    print("Matrix is Not Empty")

  result=True
  for r in range(len(matrix)):
    for c in range(len(matrix[0])):
        if r == c and matrix[r][c] != 1:
            result=False
        elif r != c and matrix[r][c]!=0:
            result=False

  if result==True:
    print("Matrix is an Identity Matrix")
  else:
    print("Matrix is not an Identity Matrix")

  MM = matrix
  OM = np.all((MM == 1))
  if OM:
    print("Matrix is a Ones Matrix")
  else:
    print("Matrix is not a Ones Matrix")
  ZM = np.all((MM == 0))
  if ZM:
    print("Matrix is a Zero Matrix")
  else: 
    print("Matrix is not a Zero Matrix")

In [ ]:
A = np.array([
    [1+2,2,5,4-1],
    [3,4,12-5, 9-1],
    [4,5*2, 16-7, 1+9],
    [1,1**2, 1+0, 21-20]          
])

mat_desc(A)

Matrix:
[[ 3  2  5  3]
 [ 3  4  7  8]
 [ 4 10  9 10]
 [ 1  1  1  1]]

Shape:	(4, 4)
Size:	16
Rank:	2

Matrix is a Square Matrix
Matrix is Not Empty
Matrix is not an Identity Matrix
Matrix is not a Ones Matrix
Matrix is not a Zero Matrix


In [ ]:
B = np.array([
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1]          
])

mat_desc(B)

Matrix:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Shape:	(4, 5)
Size:	20
Rank:	2

Matrix is Not a Square Matrix
Matrix is Not Empty
Matrix is not an Identity Matrix
Matrix is a Ones Matrix
Matrix is not a Zero Matrix


In [ ]:
C = np.array([
    [1,0,0,0,0,0],
    [0,1,0,0,0,0],
    [0,0,1,0,0,0],
    [0,0,0,1,0,0],
    [0,0,0,0,1,0],
    [0,0,0,0,0,1]          
])

mat_desc(C)

Matrix:
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]

Shape:	(6, 6)
Size:	36
Rank:	2

Matrix is a Square Matrix
Matrix is Not Empty
Matrix is an Identity Matrix
Matrix is not a Ones Matrix
Matrix is not a Zero Matrix


###Task 2


Task 2 performs matrix algebra that researchers in this experiment previously did. This program displays the two matrices provided by the researchers and determines whether the two given matrices were viable for operations or not. Once the two matrices are possible for operation, this program then performs application, subtraction, element-wise multiplication, and element-wise division of the two matrices given.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

def mat_operations(matA, matB):
    matA = np.array(matA)
    matB = np.array(matB)
    print(f'Matrix A:\n{matA}\n')
    print(f'Matrix B:\n{matB}\n')
    if(matA.shape != matB.shape):
        print('Matrix A and Matrix B are not viable for operations.')
    else:
      print('Sum of Matrix A and Matrix B:')
      matsum = matA + matB
      print(matsum)
      print('Difference of Matrix A and Matrix B:')
      matdiff = matA - matB
      print(matdiff)
      print('Element-wise Multiplication of Matrix A and Matrix B:')
      matmul = np.multiply(matA, matB)
      print(matmul)
      print('Element-wise Division of Matrix A and Matrix B:')
      mmul = np.divide(matA, matB)
      print(mmul)

In [ ]:
matA = np.array([
                 [11, 19, 20],
                 [23, 27, 21],
                 [20, 24, 23],
                 [12, 25, 14]
])

matB = np.array([
                 [12, 19, 21, 18, 24],
                 [6, 11, 22, 29, 26],
                 [3, 11, 20, 24, 18]
])
mat_operations(matA, matB)

Matrix A:
[[11 19 20]
 [23 27 21]
 [20 24 23]
 [12 25 14]]

Matrix B:
[[12 19 21 18 24]
 [ 6 11 22 29 26]
 [ 3 11 20 24 18]]

Matrix A and Matrix B are not viable for operations.


In [ ]:
matA = np.array([
                 [20, 19+5, 12*2],
                 [2*4, 27-3, 21+7],
                 [2*14, 24-1, 23+3]
])

matB = np.array([
                 [12*3, 90-64, 3**3],
                 [6+16, 11*3, 22+23],
                 [3*5*2, 11+26-3, 20*5-50]
])
mat_operations(matA, matB)

Matrix A:
[[20 24 24]
 [ 8 24 28]
 [28 23 26]]

Matrix B:
[[36 26 27]
 [22 33 45]
 [30 34 50]]

Sum of Matrix A and Matrix B:
[[56 50 51]
 [30 57 73]
 [58 57 76]]
Difference of Matrix A and Matrix B:
[[-16  -2  -3]
 [-14  -9 -17]
 [ -2 -11 -24]]
Element-wise Multiplication of Matrix A and Matrix B:
[[ 720  624  648]
 [ 176  792 1260]
 [ 840  782 1300]]
Element-wise Division of Matrix A and Matrix B:
[[0.55555556 0.92307692 0.88888889]
 [0.36363636 0.72727273 0.62222222]
 [0.93333333 0.67647059 0.52      ]]


In [ ]:
matA = np.array([
                 [23-10, 2*8, 45-23, 74-60],
                 [15+7, 27-2, 2*9, 2**4],
                 [20-3, 24+4, 3**3, 16+8],
                 [87-36, 3**2, 4**2, 14+16]
])

matB = np.array([
                 [12-6, 19-8, 2*5, 6+2],
                 [6+15, 11*1, 2**2, 65-60],
                 [3*5, 11+12, 40-20, 4*2],
                 [4**2, 16-8, 3*2, 2**4]
])
mat_operations(matA, matB)

Matrix A:
[[13 16 22 14]
 [22 25 18 16]
 [17 28 27 24]
 [51  9 16 30]]

Matrix B:
[[ 6 11 10  8]
 [21 11  4  5]
 [15 23 20  8]
 [16  8  6 16]]

Sum of Matrix A and Matrix B:
[[19 27 32 22]
 [43 36 22 21]
 [32 51 47 32]
 [67 17 22 46]]
Difference of Matrix A and Matrix B:
[[ 7  5 12  6]
 [ 1 14 14 11]
 [ 2  5  7 16]
 [35  1 10 14]]
Element-wise Multiplication of Matrix A and Matrix B:
[[ 78 176 220 112]
 [462 275  72  80]
 [255 644 540 192]
 [816  72  96 480]]
Element-wise Division of Matrix A and Matrix B:
[[2.16666667 1.45454545 2.2        1.75      ]
 [1.04761905 2.27272727 4.5        3.2       ]
 [1.13333333 1.2173913  1.35       3.        ]
 [3.1875     1.125      2.66666667 1.875     ]]
